language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6 COVERAGE=0
    - php: 5.6
      env: TYPO3_VERSION=^7.6 COVERAGE=0
    - php: 7.0
      env: TYPO3_VERSION=^7.6 COVERAGE=0
    - php: 7.1
      env: TYPO3_VERSION=^7.6 COVERAGE=0
    - php: 7.1
      env: TYPO3_VERSION=^8 COVERAGE=0
    - php: 7.0
      env: TYPO3_VERSION=^8 COVERAGE=1

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - derhansen@gmail.com

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - if [ -d .Build/vendor/typo3/testing_framework/Resources/Core/Build ]; then export TYPO3_BUILD_DIR=".Build/vendor/typo3/testing_framework/Resources/Core/Build"; else export TYPO3_BUILD_DIR=".Build/vendor/typo3/cms/typo3/sysext/core/Build"; fi

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c $TYPO3_BUILD_DIR/UnitTests.xml Tests/Unit/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c $TYPO3_BUILD_DIR/UnitTests.xml Tests/Unit/
    fi
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --coverage-clover={}functionaltest-coverage.clover --colors -c $TYPO3_BUILD_DIR/FunctionalTests.xml {}'
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      cp -R typo3conf/ext/sf_banners/.git .
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
      find 'Tests/Functional' -wholename '*Test.php' -exec php ocular.phar code-coverage:upload --format=php-clover {}functionaltest-coverage.clover \;
    fi
