language: php
php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql TYPO3=master INTEGRATION=master

notifications:
  email:
    - derhansen@gmail.com

before_script:
  - sudo apt-get update && sudo apt-get install git

# Install build dependencies
  - cd ..
  - git clone --single-branch --branch $INTEGRATION --depth 1 git://github.com/derhansen/TYPO3-Travis-Integration.git build-environment
  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core
  - source build-environment/install-helper.sh
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi

# Install rudimentary TYPO3
  - git clone --single-branch --branch $TYPO3 --depth 1 git://git.typo3.org/TYPO3CMS/Distributions/Introduction.git build-environment/Introduction
  - mv core/typo3 .
  - if [[ -d core/t3lib ]]; then mv core/t3lib . ; fi
  - mv build-environment/typo3conf .
  - git clone --single-branch --branch master --depth 1 git://git.typo3.org/TYPO3CMS/Extensions/phpunit.git typo3conf/ext/phpunit/
  - mv sf_banners ./typo3conf/ext
  - mkdir fileadmin
  - mkdir uploads
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/cache_tables.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
  - if [[ "$DB" == "mysql" && -f  build-environment/dbimport/cli_users.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
  - if [[ "$DB" == "mysql" && -f  build-environment/dbimport/sf_banners.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/sf_banners.sql; fi

# Import tables for phpunit testing framework
  - if [[ "$DB" == "mysql" && -f  build-environment/dbimport/phpunit.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/phpunit.sql; fi

script:
  - php $PWD/typo3/cli_dispatch.phpsh phpunit -c typo3conf/ext/sf_banners/Tests/Build/phpunit.xml
  - php $PWD/typo3/cli_dispatch.phpsh phpunit --coverage-clover=coverage.clover -c typo3conf/ext/sf_banners/Tests/Build/phpunit.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - cp -R typo3conf/ext/sf_banners/.git .
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
